name = "EzXML"
uuid = "8f5d6c58-4d21-5cfd-889c-e3ad7ee6a615"
authors = ["Kenta Sato <bicycle1885@gmail.com>"]
version = "1.2.2"

[deps]
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
XML2_jll = "02c8fc9c-b97f-50b9-bbe4-9be30ff0a78a"

[compat]
Printf = "1.3"
XML2_jll = "2.9.9 - 2.14"
julia = "1.6"
