name = "EzXML"
version = "0.9.1"
authors = ["Kenta Sato <bicycle1885@gmail.com>"]
uuid = "8f5d6c58-4d21-5cfd-889c-e3ad7ee6a615"

[deps]
BinaryProvider = "b99e7846-7c00-51b0-8f62-c81ae34c0232"
Libdl = "8f399da3-3557-5675-b5ff-fb832c97cbdb"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
